WITH CTE AS (


select

TO_TIMESTAMP(REPLACE(STARTED_AT,'"','')) AS STARTED_AT,
TO_TIMESTAMP(REPLACE(ENDED_AT,'"','')) AS ENDED_AT

from {{ source('demo', 'bike') }}

where STARTED_AT != 'starttime' and STARTED_AT != '"starttime"'
),


CORRECT_DATA AS (

select
STARTED_AT AS STARTED_AT,
DATE(STARTED_AT) AS DATE_STARTED_AT,
HOUR(STARTED_AT) AS HOUR_STARTED_AT,
CASE 
WHEN DAYNAME(STARTED_AT) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
CASE WHEN MONTH(STARTED_AT) in (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(STARTED_AT) in (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(STARTED_AT) in (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN' 
    END AS STATION_OF_YEAR

from
CTE

)



select 
*
from CORRECT_DATA 